[package]
name = "etherealog"
version = "0.1.0"
edition = "2024"

[dependencies]
revm = { version = "22.0.0", features = ["serde-json"] }

tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.96"
